import type { FriendListItemData, GroupListItemData } from "./types";

/**
 * Synthetic data for the list screens — display-shaped only, replaced by the
 * API later. Balances mix all three states (they owe you / you owe them /
 * settled) and avatars mix photos with initials, so every visual branch of
 * the rows is exercised.
 */

/**
 * Friend rows preview the private 1:1 INDIVIDUAL group with each friend,
 * so their activity lines are 1:1 expenses — never a shared group's name.
 */
export const MOCK_FRIENDS: FriendListItemData[] = [
  {
    id: "f01",
    name: "Andrew Ainsley",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
    balance: 1250.0,
    lastActivity: 'Added "Cab to airport" · 2h ago',
  },
  {
    id: "f02",
    name: "Charlotte Hanlin",
    avatarUrl: "https://i.pravatar.cc/150?img=47",
    balance: -728.5,
    lastActivity: 'You added "Groceries" · 5h ago',
  },
  {
    id: "f03",
    name: "Priya Sharma",
    avatarUrl: "https://i.pravatar.cc/150?img=45",
    balance: 0,
    lastActivity: "Settled up · 1d ago",
  },
  {
    id: "f04",
    name: "Rahul Mehta",
    balance: -450.5,
    lastActivity: 'Added "Lunch" · 1d ago',
  },
  {
    id: "f05",
    name: "Neha Kapoor",
    avatarUrl: "https://i.pravatar.cc/150?img=25",
    balance: 875.25,
    lastActivity: 'You added "Movie tickets" · 2d ago',
  },
  {
    id: "f06",
    name: "Vikram Singh",
    balance: -120.0,
    lastActivity: 'Added "Fuel split" · 3d ago',
  },
  {
    id: "f07",
    name: "Aarav Patel",
    avatarUrl: "https://i.pravatar.cc/150?img=11",
    balance: 15420.0,
    lastActivity: 'You added "Hotel booking" · 5d ago',
  },
  {
    id: "f08",
    name: "Ananya Gupta",
    balance: 0,
    lastActivity: "Settled up · 6d ago",
  },
  {
    id: "f09",
    name: "Rohan Desai",
    avatarUrl: "https://i.pravatar.cc/150?img=13",
    balance: -280.75,
    lastActivity: 'Added "Dinner" · 6d ago',
  },
  {
    id: "f10",
    name: "Sneha Iyer",
    balance: 95.5,
    lastActivity: 'You added "Coffee" · 1w ago',
  },
  {
    id: "f11",
    name: "Kabir Malhotra",
    avatarUrl: "https://i.pravatar.cc/150?img=15",
    balance: 0,
    lastActivity: "Settled up · 1w ago",
  },
  {
    id: "f12",
    name: "Ishita Verma",
    balance: 640.0,
    lastActivity: 'Added "Gift contribution" · 1w ago',
  },
  {
    id: "f13",
    name: "Aditya Rao",
    avatarUrl: "https://i.pravatar.cc/150?img=17",
    balance: -199.0,
    lastActivity: 'You added "Book order" · 2w ago',
  },
  {
    id: "f14",
    name: "Meera Nair",
    balance: 320.0,
    lastActivity: 'Added "Brunch" · 2w ago',
  },
  {
    id: "f15",
    name: "Arjun Joshi",
    avatarUrl: "https://i.pravatar.cc/150?img=19",
    balance: -75.0,
    lastActivity: 'Added "Court fees" · 3w ago',
  },
  {
    id: "f16",
    name: "Simran Kaur",
    balance: 0,
    lastActivity: "Settled up · Dec 2023",
  },
  {
    id: "f17",
    name: "Yash Shah",
    avatarUrl: "https://i.pravatar.cc/150?img=60",
    balance: -4520.0,
    lastActivity: 'You added "Flight tickets" · 3w ago',
  },
  {
    id: "f18",
    name: "Pooja Bhatia",
    avatarUrl: "https://i.pravatar.cc/150?img=22",
    balance: 0,
    lastActivity: "Settled up · 3w ago",
  },
  {
    id: "f19",
    name: "Harsh Mehta",
    balance: 2685.5,
    lastActivity: 'Added "Utility bill" · 1mo ago',
  },
  {
    id: "f20",
    name: "Nisha Reddy",
    avatarUrl: "https://i.pravatar.cc/150?img=24",
    balance: -1585.75,
    lastActivity: 'You added "Car rental" · 1mo ago',
  },
  {
    id: "f21",
    name: "Karan Khanna",
    balance: 312.5,
    lastActivity: 'Added "Snacks" · 1mo ago',
  },
  {
    id: "f22",
    name: "Divya Menon",
    balance: -980.25,
    lastActivity: 'You added "Stationery" · 1mo ago',
  },
  {
    id: "f23",
    name: "Aman Choudhary",
    avatarUrl: "https://i.pravatar.cc/150?img=27",
    balance: 7560.0,
    lastActivity: 'Added "Resort stay" · 1mo ago',
  },
  {
    id: "f24",
    name: "Ritika Sinha",
    balance: 0,
    lastActivity: "Settled up · 2mo ago",
  },
  {
    id: "f25",
    name: "Siddharth Jain",
    avatarUrl: "https://i.pravatar.cc/150?img=29",
    balance: -85.5,
    lastActivity: 'You added "Popcorn combo" · 2mo ago',
  },
  {
    id: "f26",
    name: "Tanvi Kulkarni",
    balance: 1540.25,
    lastActivity: 'Added "Gear rental" · 2mo ago',
  },
];

export const MOCK_GROUPS: GroupListItemData[] = [
  {
    id: "g01",
    name: "Goa Trip 2024",
    photoUrl: "https://picsum.photos/seed/goa/200",
    memberCount: 12,
    balance: 1250.0,
    lastActivity: 'Priya added "Beach shack dinner" · 2h ago',
  },
  {
    id: "g02",
    name: "Flat 402 Rent & Bills",
    icon: "home",
    memberCount: 4,
    balance: -8450.5,
    lastActivity: "Rent split for July · 5h ago",
  },
  {
    id: "g03",
    name: "Office Lunch Squad",
    icon: "briefcase",
    memberCount: 8,
    balance: -450.5,
    lastActivity: 'Vikram added "Biryani Friday" · 1d ago',
  },
  {
    id: "g04",
    name: "College Friends",
    photoUrl: "https://picsum.photos/seed/college/200",
    memberCount: 15,
    balance: 0,
    lastActivity: "Everyone settled up · 2d ago",
  },
  {
    id: "g05",
    name: "Weekend Trek Crew",
    icon: "sunrise",
    memberCount: 7,
    balance: 875.25,
    lastActivity: 'Aarav added "Permits & cab" · 2d ago',
  },
  {
    id: "g06",
    name: "Cricket Sundays",
    icon: "target",
    memberCount: 14,
    balance: -120.0,
    lastActivity: "Ground booking split · 3d ago",
  },
  {
    id: "g07",
    name: "Family",
    photoUrl: "https://picsum.photos/seed/family/200",
    memberCount: 6,
    balance: 0,
    lastActivity: "Mom settled groceries · 4d ago",
  },
  {
    id: "g08",
    name: "Ladakh Road Trip",
    photoUrl: "https://picsum.photos/seed/ladakh/200",
    memberCount: 5,
    balance: 15420.0,
    lastActivity: 'You added "Fuel + tolls" · 5d ago',
  },
  {
    id: "g09",
    name: "Movie Nights",
    icon: "film",
    memberCount: 9,
    balance: -280.75,
    lastActivity: 'Sneha added "IMAX tickets" · 6d ago',
  },
  {
    id: "g10",
    name: "Gym Buddies",
    icon: "activity",
    memberCount: 3,
    balance: 0,
    lastActivity: "Protein order settled · 1w ago",
  },
  {
    id: "g11",
    name: "Diwali Party 🪔",
    icon: "gift",
    memberCount: 22,
    balance: 640.0,
    lastActivity: "Decorations & sweets · 1w ago",
  },
  {
    id: "g12",
    name: "Book Club",
    icon: "book-open",
    memberCount: 6,
    balance: -199.0,
    lastActivity: "Monthly picks order · 2w ago",
  },
  {
    id: "g13",
    name: "Hostel Wing B",
    photoUrl: "https://picsum.photos/seed/hostel/200",
    memberCount: 18,
    balance: 95.5,
    lastActivity: "Midnight Maggi run · 2w ago",
  },
  {
    id: "g14",
    name: "Startup Lunches",
    icon: "coffee",
    memberCount: 5,
    balance: 0,
    lastActivity: "All squared away · 3w ago",
  },
  {
    id: "g15",
    name: "Badminton Group",
    icon: "wind",
    memberCount: 10,
    balance: -75.0,
    lastActivity: "Court fees for June · 3w ago",
  },
  {
    id: "g16",
    name: "Secret Santa 2023",
    icon: "gift",
    memberCount: 11,
    balance: 0,
    lastActivity: "Wrapped up · Dec 2023",
  },
];
